mikov: homework_15. done
eugene-okulik/Dire pull request #14
Opened 2024-04-27 09:55 UTC by MaxM55

2024-04-29 09:54 UTC, eugene-okulik requested changes
Местами ты используешь питоновские подстановки с помощью `f'stirng'` а местами используешь подстановки, защищенные от инъекций. Правильнее везде использовать один и тот же подход. Ну, и лучше привыкать всегда использовать безопасные подстановки.

2024-04-29 09:54 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_15/database.py
> +# Создайте группу (group)
Первое задание

> Создайте студента

2024-04-29 09:54 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_15/database.py
> +# Создайте студента (student) и определите своего студента в группу
Это задание звучит иначе

> Создайте группу (group) и определите своего студента туда

2024-04-30 13:38 UTC, MaxM55 commented on homework/maksim_mikov/Homework_15/database.py
> +# Создайте группу (group)
По поводу подстановок.
просто думал показать различные варианты подстановок
Откорректирую

2024-04-30 14:23 UTC, MaxM55 commented on homework/maksim_mikov/Homework_15/database.py
> +# Создайте студента (student) и определите своего студента в группу
Просто в прошлый раз от тебя было замечание: 
"Скорее всего, ты делал не в том порядке, в котором у тебя идут команды. Иначе, откуда у тебя id группы для студента еще в момент, когда группа не создана.
Ну, в следующем задании вся последовательность будет видна."
Вот я и решил показать что сначала создаю группу, а потом при создании студента сразу определяю его в созданную группу, путём указании group_id как делал в прошлый раз. )

2024-05-01 09:55 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_15/database.py
> +# Создайте студента (student) и определите своего студента в группу
Я еще тогда хотел прицепиться, что ты взял и избежал того, что студента нужно проапдейтить. Если выполнять всё задание так, как написано, то студент создается с пустой группой, а потом ему апдейтом группа проставляется. А ты изменил задание. Результат то тот же, но фишка была в том, чтобы хоть раз за задание поиспользовать UPDATE  
А теперь пойду смотреть как ты исправил

2024-05-01 09:58 UTC, eugene-okulik approved these changes
Отлично.  
И защищенных подстановок добавил, вроде бы.  
Но все равно остались и те и другие. Консистентность лучше чем разные подходы. Мы ж как тестеры даже проверять должны на консистентность. )))

2024-05-01 09:58 UTC, merged