mikov: homework_23.done
eugene-okulik/Dire pull request #22
Opened 2024-06-24 07:37 UTC by MaxM55

2024-06-24 09:22 UTC, eugene-okulik requested changes
Всё хорошо, но нужно избавиться от ошибки Линта.  
А для чего вообще нужен файл lesson_23.py?

2024-06-24 09:22 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_23/homework_23.py
> +    service = Service(GeckoDriverManager().install())
А для чего ты сам устанавливаешь драйверы? Селениум сам не справился?

2024-06-24 11:39 UTC, MaxM55 commented on homework/maksim_mikov/Homework_23/homework_23.py
> +    service = Service(GeckoDriverManager().install())
Ошибки линта поправил.

> А для чего ты сам устанавливаешь драйверы? Селениум сам не справился?
**Нашёл такое решение**
Вообще мне этот сайт весь мозг вынес со своей долгой загрузкой, со своими дропдаунами, которые при этом не являются селектами, чекбоксами которые прячутся и т.д. 

> А для чего ты сам устанавливаешь драйверы? Селениум сам не справился?

2024-06-25 08:26 UTC, eugene-okulik approved these changes

2024-06-25 08:26 UTC, merged