mikov: homework_10. done
eugene-okulik/Dire pull request #9
Opened 2024-04-03 10:08 UTC by MaxM55

2024-04-04 08:51 UTC, eugene-okulik requested changes

2024-04-04 08:51 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_10/homework_10_list_comprehension.py
> +price_dict = {item.split()[0]: int(item.split()[1].replace('р', '')) for item in price_list}
:+1:

2024-04-04 08:51 UTC, eugene-okulik commented on homework/maksim_mikov/Homework_10/homework_10_task_2.py
> +        print(text)
Эта функция должна выглядеть ровно так же как в задании
```python
@repeat_me
def example(text):
    print(text)
```
А вот декоратор нужно сделать так, чтобы он несколько раз вызывал эту функцию.

2024-04-04 12:09 UTC, MaxM55 commented on homework/maksim_mikov/Homework_10/homework_10_task_2.py
> +        print(text)
Исправил

2024-04-05 10:02 UTC, eugene-okulik approved these changes

2024-04-05 10:02 UTC, merged